services:
  hp-tuning:
    image: mlops2_hp-tuning:dev
    build: .
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./miopen-cache:/tmp/miopen-cache
    ipc: host
    shm_size: 8gb

  hp-tuning-amd:
    extends: hp-tuning
    profiles: ["amd"]
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - PYTHONUNBUFFERED=1
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - MIOPEN_DISABLE_CACHE=0
      - MIOPEN_USER_DB_PATH=/tmp/miopen-cache
      - MIOPEN_CUSTOM_CACHE_DIR=/tmp/miopen-cache
      - AMD_LOG_LEVEL=1
    
    privileged: true
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
      - systempaths=unconfined
    cap_add:
      - ALL
    

  hp-tuning-nvidia:
    extends: hp-tuning
    profiles: ["nvidia"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]